# SPDX-License-Identifier: GPL-2.0-only
"""AITD1 language PAKs: decode them to editable UTF-8 text and pack them back.

Entry 0 holds the messages (`@<num>:<text>` lines), entries 1-21 the documents
(codes #P page, #T tab, #C centre, #G<n> image). Every entry ends at 0x1A.
"""
from __future__ import annotations

import re
import struct

ENTRY_COUNT = 22
END = b"\x1a\r\n"
# The game font draws 0xA9 as (c); CP850 has (R) there.
_DECODE_OVERRIDES = {0xA9: "©"}
_ENCODE_OVERRIDES = {v: k for k, v in _DECODE_OVERRIDES.items()}

# Composed by TatouSource/FitdLib/text/fontCompose.cpp kComposed: code -> (base, mark donor).
COMPOSED = {0xC6: (ord("a"), 0xA4), 0xE4: (ord("o"), 0xA4)}
# Drawn as the plain capital in the bitmap font (fontCompose.cpp kPlainCapitals).
PLAIN_CAPITALS = {0xB7: ord("A"), 0xB5: ord("A"), 0xB6: ord("A"), 0xC7: ord("A"), 0xD2: ord("E"),
                  0xD6: ord("I"), 0xE0: ord("O"), 0xE2: ord("O"), 0xE5: ord("O"), 0xE9: ord("U")}
# Letters the original bitmap font draws beyond printable ASCII, as the game uses them.
_FONT_LETTERS = "áéíóúâêôàçüëÇÉ©·"
ALLOWED = (set(chr(c) for c in range(0x20, 0x7F)) | set(_FONT_LETTERS)
           | {bytes([c]).decode("cp850") for c in COMPOSED}
           | {bytes([c]).decode("cp850") for c in PLAIN_CAPITALS} | {"\n"})

_MESSAGE = re.compile(r"^@(\d+):", re.MULTILINE)
_IMAGE = re.compile(r"#G\d+")


def entry_file(i: int) -> str:
    """Source file name of entry i: messages.txt, doc01.txt ... doc21.txt."""
    return "messages.txt" if i == 0 else f"doc{i:02d}.txt"


def decode(entry: bytes) -> str:
    """Entry bytes (up to 0x1A) -> text with '\\n' line ends."""
    end = entry.find(0x1A)
    body = entry if end < 0 else entry[:end]
    chars = (_DECODE_OVERRIDES.get(b) or bytes([b]).decode("cp850") for b in body)
    return "".join(chars).replace("\r\n", "\n")


def _normalise(text: str) -> str:
    return text.removeprefix("\ufeff").replace("\r\n", "\n")


def encode(text: str) -> bytes:
    """Text -> entry bytes: CP850 (0xA9 = (c)), '\\r\\n' line ends, 0x1A end."""
    out = bytearray()
    for ch in _normalise(text).replace("\n", "\r\n"):
        out += bytes([_ENCODE_OVERRIDES[ch]]) if ch in _ENCODE_OVERRIDES else ch.encode("cp850")
    return bytes(out) + END


def bad_chars(text: str) -> list[tuple[int, str]]:
    """(line number, character) for every character the bitmap font cannot draw."""
    found = []
    for n, line in enumerate(_normalise(text).split("\n"), start=1):
        found += [(n, ch) for ch in dict.fromkeys(line) if ch not in ALLOWED]
    return found


def message_numbers(text: str) -> list[int]:
    return [int(m) for m in _MESSAGE.findall(text)]


def image_codes(text: str) -> list[str]:
    return _IMAGE.findall(text)


def validate(pt: list[bytes], en: list[bytes]) -> list[str]:
    """Problems with the Portuguese entries against the English ones."""
    problems = []
    pt_nums, en_nums = message_numbers(decode(pt[0])), message_numbers(decode(en[0]))
    missing = [n for n in en_nums if n not in pt_nums]
    extra = [n for n in pt_nums if n not in en_nums]
    if missing:
        problems.append("messages: missing " + ", ".join(f"@{n}" for n in missing))
    if extra:
        problems.append("messages: extra " + ", ".join(f"@{n}" for n in extra))
    for i in range(1, min(len(pt), len(en))):
        got, want = image_codes(decode(pt[i])), image_codes(decode(en[i]))
        if got != want:
            problems.append(f"doc{i:02d}: image codes {got} != English {want}")
    return problems


def pak_image(entries: list[bytes]) -> bytes:
    """A PAK of raw (flag 0) entries, in the layout the engine and pak.Pak read:
    u32 0, u32 offsets[n], then per entry u32 0, u32 size, u32 size, u8 flag,
    u8 info5, u16 name_len, payload."""
    blobs = [struct.pack("<IIIBBH", 0, len(e), len(e), 0, 0, 0) + e for e in entries]
    pos, offsets = 4 * (len(entries) + 1), []
    for blob in blobs:
        offsets.append(pos)
        pos += len(blob)
    return struct.pack("<I", 0) + b"".join(struct.pack("<I", o) for o in offsets) + b"".join(blobs)


def embedded_cpp(name: str, data: bytes) -> str:
    """The embedded/ source for <name>.PAK, in the format of the generated files."""
    rows = [", ".join(f"0x{b:02X}" for b in data[i:i + 16]) for i in range(0, len(data), 16)]
    body = ",\n".join("    " + r for r in rows)
    return ("///////////////////////////////////////////////////////////////////////////////\n"
            "// Alone In The Dark Re-Haunted\n"
            "// Generated by tools/lang.py pack from Assets/lang - DO NOT EDIT\n"
            "///////////////////////////////////////////////////////////////////////////////\n\n"
            f"extern const unsigned char embdata_{name}_PAK[] = {{\n{body}\n}};\n\n"
            f"extern const unsigned long long embdata_{name}_PAK_size = {len(data)}ULL;\n")
